name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  DENO_DIR: ../.deno_cache

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    timeout-minutes: 5
    runs-on: ${{ matrix.os }}

    steps:
      - name: 🏴‍☠️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: deno-v2-${{ matrix.os }}-${{ hashFiles('main.ts', 'deno.jsonc') }}

      - name: 🦕 Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: 🩺 Format
        if: startsWith(matrix.os, 'ubuntu')
        uses: dprint/check@v2.0

      - name: 👩‍⚕️ Lint
        if: startsWith(matrix.os, 'ubuntu')
        run: deno lint

      - name: 🩺 Typecheck
        run: deno task typecheck
        shell: bash
